spring:
    jpa:
       database-platform: org.hibernate.dialect.H2Dialect
       hibernate:
            ddl-auto: update
       properties:
            hibernate:
                format_sql: true
                generate_statistics: false
       show-sql: true   
    h2:
       console:
            enabled: true
            path: /h2-console 
    datasource:
       url: jdbc:h2:mem:inventory
       username: sa
       password: sa
       driver-class-name: org.h2.Driver
       initialization-mode: always
       
logging:
    pattern:
        console: '%d{yyyy-MM-dd HH:mm:ss} - %msg%n'
