spring:
  datasource:
    url: jdbc:postgresql://mypostgres:5432/asset_management_db
    username: postgres
    password: secret
    initialization-mode: always
    schema:
        - classpath:/schema-postgres.sql
 
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
       dialect: org.hibernate.dialect.PostgreSQLDialect
      
  


    

      
     
