version: '3'
services:
  database:
    image: "postgres"
    env_file:
      - database.env 
    ports:
      - 5431:5432
    volumes:
      - database-data:/var/lib/postgresqla/data/ 
        # command: -p 5433
volumes:
  database-data: # named volumes can be managed easier using docker-compose
